### ISSUE TITLE
Snack is huge on mobile devices.

### ISSUE THREAD

**Issue by usama-asfar** [iamhosseindhv/notistack#221]
![5e302d587ae1c761c23d51c30](https://user-images.githubusercontent.com/42825498/73281527-21159e00-4216-11ea-9812-00635d20b0c8.png)

**Comment by davwheat** [comment]
That's due to the button you've added as it's overflowing to a new line with some margins.

**Comment by m3h0w** [comment]
I have the same issue - couldn't find a simple way to fix it.

Seems like this is going to be a reoccurring problem for the library, since material ui's snackbar by default has that button, while notistack removes it and requires the user to reinsert it.

**Comment by iamhosseindhv** [comment]
This is expected. Button will be on a new line as you can see on mat ui docs:
https://material-ui.com/components/snackbars/#message-length

But I agree in looks weird IF you're using an [`IconButton`](https://material-ui.com/components/buttons/#icon-buttons) instead of [`Button`](https://material-ui.com/components/buttons/#text-buttons).
