### ISSUE TITLE
Ignore particular message by removing from stack

### ISSUE THREAD

**Issue by jeevasusej** [iamhosseindhv/notistack#258]
Hi,

I have implemented the snackbar with the following options.
maxSnack={1}, preventDuplicate.

I want a particular snackbar that should not removed from stack automatically when we have continuous 3 messages.
Is there any options?

**Comment by iamhosseindhv** [comment]
If I'm understanding this right, you want the other 2 snackbars to be blocked and not displayed until the first one is closed. Currently there's no support for this.

You can use `persist: true` for the snackbar to stay on the screen, but since `maxSnack={1}`, snackbar will be dismissed once the second/third snackbars are `enqueue`d.
