### ISSUE TITLE
Snackbars stop showing after few clicks

### ISSUE THREAD

**Issue by nebojsanb** [iamhosseindhv/notistack#270]
Great tool first of all. Thank you for sharing it.

I am testing some login logic and I generated few (~4) Snackbars in a few seconds. I noticed that after that, they stopped showing up altogether.

## Expected Behavior
I believe that they should show up all the time unless configured differently.

## Current Behavior
After a few clicks, they stop appearing. I also noticed that after the third one (in most of the cases but not always) the fourth one is shown with a few sec delay. After that, no more Snackbars are shown on the screen. In my app maxSnack={3}.

## Steps to Reproduce
In codesandbox.io I had to click more times comparing to my app, but eventually (maybe 10-15 times) it also stopped working.

Link:
https://codesandbox.io/embed/eager-einstein-1rno0?fontsize=14&hidenavigation=1&theme=dark

## Your Environment
"react-dom": "^16.13.1"
"@material-ui/core": "^4.9.14"
"notistack": "^0.9.14"
Browser: Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by rutzfutz** [comment]
I have the same issue. This is new with 0.9.14. If I downgrade to 0.9.13, everything starts working again.

**Comment by iamhosseindhv** [comment]
Thanks for reporting this guys. 

This bug was introduced by material-ui's [latest changes](https://github.com/mui-org/material-ui/commit/1f68cebd858847aa358ee6be9504550f00bc4345#diff-e6c986869658052eca777b7d7dfd352aR141) (about a week ago) in handling `react-transition-group` callbacks.

Recent changes in `v0.9.14` made the bug visible to the end users. Anyhow, it is fixed and going to be published in a few hours.

**Comment by xuxusheng** [comment]
the same to me，it took me hours to check
