### ISSUE TITLE
Missing string types in 'classes' prop

### ISSUE THREAD

**Issue by pbartkowiak-fandom** [iamhosseindhv/notistack#404]
### Context
I am able to pass a `contentRoot` key to the `classes` prop in the `SnackbarProvider` like this:

```javascript
<SnackbarProvider classes={{ contentRoot: classes.contentRoot }} />
```
It works as intended. However, `contentRoot` is not recognized as a proper key in the `classes` prop due to its typing in `index.d.ts`:
```typescript
export interface SnackbarProviderProps extends SharedProps {
    classes?: Partial<ClassNameMap<CombinedClassKey>>;
```
IDE highlights it as an error as expected:
![image](https://user-images.githubusercontent.com/82457200/125288195-20939900-e31e-11eb-9e22-3bc001335e1e.png)

### Your Environment
Notistack v. 1.0.9

**Comment by iamhosseindhv** [comment]
This is intentional. `contentRoot` is not documented in TS definitions because it's internal implementation and notistack doesn't guarantee that you can still apply your customisations through `contentRoot` in future versions.

You can continue using `contentRoot` on your own risk but it won't be officially supported and documented.

What is officially supported is using `className` prop on `SnackbarProvider` to apply the same customisations. [See the code](https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarItem/SnackbarItem.tsx#L232-L236). The both work the same.
