### ISSUE TITLE
Style SnackbarContainer-root using mui v5

### ISSUE THREAD

**Issue by pantelispanayiotou** [iamhosseindhv/notistack#448]
Hello, 
I 've been using notistack (2.0.2) along with material ui v5 and it works fine. The only problem is that i can't control the style of the SnackbarContainer. For example i need to change the padding on the top and it seems that i can do it only with classes which are not supported if you don't have makeStyles. I 've tried to use styled and create a new StyledSnackbarProvider component like so:

```
const StyledSnackbarProvider = styled(SnackbarProvider)(() => ({
    '&.MuiSnackbarContainer-top': {
     paddingTop:20
}
});
```
But it doesn't work. Ideas?

**Comment by gvorbeck** [comment]
I had to solve this because Snackbars were not getting any space between each other. However, I couldn't directly access the `SnackbarContainer-root` element no matter what I tried. `styled()` didn't work as you tried and `makeStyles()` is deprecated. So nothing was touching `.SnackbarContainer-root` no matter what I tried and all I wanted to do was add `gap: 2`.

My solution:
I moved the `<SnackbarProvider />` component further into my application's JSX, placing it directly inside my `<main />` div:
```
// I use the Stack component to group site's <header />, <main />, and <footer />
<Stack
  sx={{
  // Site-wide styles go here
  ...
  '& .SnackbarContainer-root': {
    gap: 2,
   },
  }}
>
...
  // My <main /> div
  <Container component="main">
    <SnackbarProvider>
      {children}
    </SnackbarProvider>
  </Container>
...
</Stack>
