### ISSUE TITLE
Unmet peer dependency "prop-type" "classnames"

### ISSUE THREAD

**Issue by VincentLanglet** [iamhosseindhv/notistack#72]
## Expected Behavior
`yarn` gives no warning

## Current Behavior
`yarn` gives two unmet peer dependency warning

## Steps to Reproduce
`yarn add notistack`

## Context
I have a typescript project. I have no reason to add `prop-types` in mine.
I think `prop-types` and `classnames` should be dependencies and not peerDependencies.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.4.2 |

**Comment by oliviertassinari** [comment]
@iamhosseindhv What do you think of making `classnames` a dependency instead of a peer dependency? You can benchmark the other libraries, it's what most maintainers do. If your concern is with the potential bundle duplication, you can make the accepted scope wide.

Alternatively, you can replace the package with [clsx](https://github.com/lukeed/clsx). We have replaced classnames usage with clsx in Material-UI v4-alpha.

**Comment by oliviertassinari** [comment]
The React team encourages the usage of `prop-type` as a dependency.

**Comment by VincentLanglet** [comment]
@oliviertassinari Thanks, let me buy you a 🍔for your interest !

**Comment by oliviertassinari** [comment]
@VincentLanglet Il faut essayer Cojean maintenant !

**Comment by iamhosseindhv** [comment]
Thanks @oliviertassinari and @VincentLanglet. I'll move them both to `dependencies`.  And it'll be published in the next version. [CHANGELOG](https://github.com/iamhosseindhv/notistack/blob/master/CHANGELOG.md)
